### ISSUE TITLE
Refactor Generators

### ISSUE THREAD

**Issue by klangner** [klangner/dsp#11]
Add SignalGen::new()

**Comment by garro95** [comment]
While refactoring generators, you could consider using `impl Fn(f64)->Complex64` to avoid the allocation of the `Box`, making the `struct SignalGen` generic.

**Comment by klangner** [comment]
This makes sense.
But since I haven't used Rust for the while I need to learn how to do it first :-)
Most of the time I've got borrow check on my way.

Any suggestions are appreciate!

**Comment by garro95** [comment]
Yes, in fact this is new syntax. You can see https://rust-lang-nursery.github.io/edition-guide/rust-2018/trait-system/impl-trait-for-returning-complex-types-with-ease.html and the following chapters.
In this case the struct should look like
```rust
pub struct SignalGen<F>
where F: impl Fn(f64) -> Complex64 {
    gen: Box<T>,
}
```
and the constructors should have the signature
```rust
pub fn impulse() -> SignalGen<impl Fn(f64) -> Complex64>{
  ...
}
```
The body of the functions should be the same, but without the `Box`

**Comment by klangner** [comment]
Thanks for the tip!

The problem is that now it looks ugly :-(

```rust
pub fn impulse() -> SignalGen{
  ...
}
```
looks much more better then
```rust
pub fn impulse() -> SignalGen<impl Fn(f64) -> Complex64>{
  ...
}
```
:-(

**Comment by garro95** [comment]
I don't think there is (currently) a way to express the same thing obtaining the same performances with a syntax that looks nicer.

**Comment by garro95** [comment]
I think you could merge the refactoring. What's stopping you?
