### ISSUE TITLE
Reexport num_complex

### ISSUE THREAD

**Issue by BartMassey** [klangner/dsp#16]
As far as I can tell, the `num-complex` crate is not re-exported by `dsp`. This means that working with complex numbers directly requires tracking `dsp`'s version manually in `Cargo.toml`.

I would suggest putting `pub use num_complex` in `lib.rs` and having the other modules pull it from there.

**Comment by klangner** [comment]
Yes, that's make sense. Even the examples re imports `num-complex`.
